# Generated by Django 4.0.2 on 2022-02-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Product',
        ),
    ]
