# Generated by Django 4.0.2 on 2022-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_product_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='high_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
