# Generated by Django 4.0.2 on 2022-02-17 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_item_adder_alter_item_high_bid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='adder',
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
