# Generated by Django 4.0.2 on 2022-02-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_item_adder_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bids_number',
            field=models.IntegerField(default=0),
        ),
    ]
