# Generated by Django 4.0.2 on 2022-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_item_bids_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
