# Generated by Django 4.0.2 on 2022-02-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_item_picture_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bids_number',
            new_name='bid_number',
        ),
    ]
