# Generated by Django 4.0.2 on 2022-02-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_rename_bids_number_item_bid_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_listing_id',
        ),
    ]
