# Generated by Django 4.0.2 on 2022-02-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_delete_category_remove_user_created_listing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bid',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
