# Generated by Django 4.0.2 on 2022-02-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_comment_txt_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='txt',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
