# Generated by Django 4.0.2 on 2022-02-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_comment_txt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='txt',
            new_name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
