# Generated by Django 4.0.2 on 2022-02-26 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_watchlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.item'),
        ),
    ]
