# Generated by Django 4.0.2 on 2022-02-26 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_remove_item_bid_bid_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='item_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.item'),
        ),
    ]
